"""Draw docs/architecture.png (matplotlib)."""
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch

fig, ax = plt.subplots(figsize=(13, 7.2), dpi=150)
ax.set_xlim(0, 13); ax.set_ylim(0, 7.2); ax.axis("off")


def box(x, y, w, h, title, lines, color, tc="white"):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.05,rounding_size=0.15", fc=color, ec="#333333", lw=1.2))
    ax.text(x + w / 2, y + h - 0.32, title, ha="center", va="top", fontsize=12.5, weight="bold", color=tc)
    ax.text(x + w / 2, y + h - 0.8, "\n".join(lines), ha="center", va="top", fontsize=9.3, color=tc, linespacing=1.45)


def arrow(x1, y1, x2, y2, label="", dy=0.18):
    ax.annotate("", xy=(x2, y2), xytext=(x1, y1), arrowprops=dict(arrowstyle="-|>", lw=1.8, color="#333333"))
    if label:
        ax.text((x1 + x2) / 2, (y1 + y2) / 2 + dy, label, ha="center", va="bottom", fontsize=9, color="#222222",
                bbox=dict(fc="white", ec="none", pad=1.5))


ax.text(6.5, 7.0, "MoSJE Product 1 platform – hosting architecture (synthetic data)", ha="center", va="top",
        fontsize=15, weight="bold")
ax.add_patch(FancyBboxPatch((2.55, 0.35), 10.2, 5.95, boxstyle="round,pad=0.05,rounding_size=0.2", fc="#F3F7FB",
                            ec="#2F5597", lw=1.5, ls="--"))
ax.text(2.8, 6.15, "Render (region: Singapore) – created by the render.yaml Blueprint", fontsize=10.5, color="#2F5597",
        weight="bold", va="top")

box(0.1, 3.0, 2.1, 2.2, "User", ["web browser", "(product team,", "reviewers)"], "#7F7F7F")
box(3.0, 3.0, 2.8, 2.6, "mosje-dashboard", ["Streamlit web service", "(free plan)", "Funnel · Scenarios ·", "Queues · Drill-down ·",
                                             "Admin buttons", "reads ONLY the API"], "#548235")
box(6.6, 3.0, 2.9, 2.6, "mosje-api", ["FastAPI web service (free)", "/docs  ·  X-API-Key auth", "/admin/seed · /pipeline/run",
                                       "/results/* · /student/*", "runs the mosje engine", "(linkage + eligibility)"], "#2F5597")
box(10.2, 3.0, 2.4, 2.6, "mosje-db", ["Render Postgres (free)", "inputs: JA members,", "CBSE results, schemes", "results: link_decisions,",
                                       "eligibility_results,", "outreach_queue"], "#C55A11")
box(6.6, 0.6, 2.9, 1.7, "Repo files (GitHub)", ["data/*.csv.gz (synthetic)", "Scholarship Master xlsx", "db/migrations/*.sql"], "#BF8F00")
box(3.0, 0.6, 2.8, 1.7, "mosje-shared", ["environment group", "API_KEY (generated by Render)", "shared by API + dashboard"], "#7030A0")

arrow(2.2, 4.1, 3.0, 4.1, "HTTPS")
arrow(5.8, 4.3, 6.6, 4.3, "")
ax.text(6.2, 4.15, "HTTPS +\nAPI key", ha="center", va="top", fontsize=7.8)
arrow(9.5, 4.3, 10.2, 4.3, "SQL")
arrow(8.05, 2.3, 8.05, 3.0, "seed reads", dy=-0.05)
arrow(4.4, 2.3, 4.4, 3.0, "API_KEY", dy=-0.05)
arrow(5.8, 2.2, 6.75, 3.0, "")
ax.text(6.15, 2.45, "API_KEY", fontsize=8.5, ha="center", bbox=dict(fc="white", ec="none", pad=1))
ax.text(6.5, 0.12, "Real Jan Aadhaar / CBSE data must NOT be hosted here – production belongs on NIC / MeghRaj.",
        ha="center", fontsize=10, color="#C00000", weight="bold")
plt.savefig("docs/architecture.png", bbox_inches="tight", facecolor="white")
print("saved docs/architecture.png")
